name: aliexpress_sdk
description: A dart implementation for aliexpress sdk
version: 1.0.0
repository: https://github.com/aidanahram/aliexpress-sdk

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  http: ^0.13.6
  requests: ^4.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
