name: aliexpress_sdk
description: 
  A dart implementation for aliexpress sdk based on the official python sdk. 
  Used to communicate with the aliexpress opensea api.
  Comes with functions to generate hash for secret key.

version: 1.1.0
repository: https://github.com/aidanahram/aliexpress-sdk

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
